- hosts: all
  become_user: root
  tasks:
    - get_url: 
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: ./google-chrome.deb
    - command: dpkg -i google-chrome.deb
