- hosts: all
  become_user: root
  tasks:
    - name: Download sidekick deb file
      get_url:
        url: https://cdn.meetsidekick.com/browser-builds/sidekick-linux-release-x64-112.44.2.32802-45677a6.deb
        dest: ./sidekick.deb

    - name: Depackage sidekick deb
      command: dpkg -i sidekick.deb

    - name: Install sidekick browser
      command: apt install -yf
      
    - name: Remove unused package sources
      file:
        state: absent
        path: /etc/apt/sources.list.d/sidekick-browser.list
