---
- hosts: all
  tasks: 
    - name: Install needed packages (Debian)
      package:
        name:
          - xclip
          - htop
          - graphviz
          - curl
          - build-essential
          - openssl
          - libreadline6-dev
          - zlib1g
          - zlib1g-dev
          - libssl-dev
          - libyaml-dev
          - libreadline-dev
          - libsqlite3-dev
          - libxslt1-dev
          - libgdbm-dev
          - libncurses5-dev
          - libncursesw5-dev
          - libbz2-dev
          - libsqlite3-dev
          - llvm
          - xz-utils
          - tk-dev
          - automake
          - libtool
          - bison
          - libffi-dev
          - liblzma-dev
          - libsqlite3-0
          - libmysqlclient-dev
          - aptitude
          - openvpn
          - vlc
          - postgresql
          - gparted
          - arduino
          - arduino-core
          - ffmpeg
          - net-tools
          - libpq-dev
          - ruby-dev
          - redis-server
          - cmake
          - ncdu
          - mumble
          - libpq-dev
          - libmagickwand-dev
          - gimp
          - gnome-tweaks
      become: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Install needed packages (Omarchy)
      package:
        name:
          - xclip
          - htop
          - graphviz
          - curl
          - base-devel
          - openssl
          - readline
          - zlib
          - sqlite
          - llvm
          - xz
          - tk
          - automake
          - libtool
          - bison
          - libffi
          - openvpn
          - vlc
          - postgresql
          - gparted
          - arduino
          - ffmpeg
          - net-tools
          - libpqxx
          - ruby
          - redis
          - cmake
          - ncdu
          - mumble
          - imagemagick
          - gimp
          - gnome-tweaks
      when: ansible_pkg_mgr == 'pacman'
    - command: "dpkg --add-architecture i386"
      become: true
