- hosts: all
  become_user: root
  vars:
    name: "Pavel Kalashnikov"
    email: "kalashnikovisme@gmail.com"
  tasks:
    - name: Remove apt lock file
      file:
        state: absent
        path: "/var/lib/dpkg/lock-frontend"
      become: true
    - name: Install git
      apt:
        pkg:
          - git
    - command: git config --global user.email "{{ email }}"
    - command: git config --global user.name "{{ name }}"
    - command: git config --global core.excludesfile ~/.gitignore
    - command: git config --global core.editor "vim"
    - command: git config --global init.defaultBranch "main"
    - name: Remove apt lock file
      file:
        state: absent
        path: "/var/lib/dpkg/lock-frontend"
      become: true
    - name: Install git-flow
      apt:
        pkg:
          - git-flow
    - copy:
        src: "./files/gitignore"
        dest: "~/.gitignore"
