- hosts: all
  become_user: root
  tasks:
    - name: Install obs && virtual camera
      apt:
        pkg:
          - v4l2loopback-dkms
    - name: Update repository for OBS
      shell: sudo add-apt-repository ppa:obsproject/obs-studio
      shell: sudo apt update
    - name: Install obs
      apt:
        pkg:
          - obs-studio
