---
- hosts: all
  vars:
    name: "Pavel Kalashnikov"
    email: "kalashnikovisme@gmail.com"
  tasks:
    - command: git config --global user.email "{{ email }}"
    - command: git config --global user.name "{{ name }}"
    - apt: name={{ item }}
      with_items:
        - htop 
        - graphviz 
        - git 
        - curl 
        - build-essential 
        - openssl 
        - libreadline6 
        - libreadline6-dev
        - zlib1g 
        - zlib1g-dev 
        - libssl-dev 
        - libyaml-dev 
        - libreadline-dev 
        - libsqlite3-dev 
        - libxslt1-dev 
        - libgdbm-dev 
        - libncurses5-dev 
        - automake 
        - libtool 
        - bison 
        - libffi-dev 
        - libsqlite3-0 
        - libmysqlclient-dev 
    - shell: "curl -sSL https://get.rvm.io | bash -s stable"
      tags: rails
    - lineinfile: line="source /home/pavel/.rvm/scripts/rvm" dest="~/.bashrc" state=present
    - file: path="~/.gemrc" state=touch
    - lineinfile: 'line="gem: --no-ri --no-rdoc" dest="~/.gemrc"'
    - file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
      with_items:
        - gitignore
        - vimrc
    - apt: name=git-flow
    - apt: name=vim
      tags: vim
    - git: repo=https://github.com/ingydotnet/yaml-vim.git
           dest=~/vim_files
      tags: vim
    - file: path=~/.vim/synta state=directory
    - copy: src=~/vim_files/syntax/yaml.vim dest=~/.vim/syntax/yaml.vim
      tags: vim
    - file: path=~/.vim/scripts state=directory
      tags: vim
    - copy: src=~/vim_files/{{ item }} dest=~/.vim/scripts/{{ item }}
      tags: vim
      with_items:
        - yamlsort.vim
        - yamlsort.rb
    - file: path=~/vim_files state=absent
    - command: git config --global core.editor "vim"
      tags: vim
      tags: vim
