---
- hosts: all
  vars:
    name: "Pavel Kalashnikov"
    email: "kalashnikovisme@gmail.com"
  tasks: 
    - command: git config --global user.email "{{ email }}"
    - command: git config --global user.name "{{ name }}"
    - apt: name={{ item }}
      sudo: True
      with_items:
        - htop 
        - graphviz 
        - git 
        - curl 
        - build-essential 
        - openssl 
        - libreadline6 
        - libreadline6-dev
        - zlib1g 
        - zlib1g-dev 
        - libssl-dev 
        - libyaml-dev 
        - libreadline-dev 
        - libsqlite3-dev 
        - libxslt1-dev 
        - libgdbm-dev 
        - libncurses5-dev 
        - automake 
        - libtool 
        - bison 
        - libffi-dev 
        - libsqlite3-0 
        - libmysqlclient-dev 
        - aptitude
        - openvpn
        - vim-nox
        - vim-gtk
        - vim-gnome
        - vim-athena
        - vlc
        - postgresql
    #- command: "curl -sSL https://get.rvm.io | bash -s stable --rails"
    - lineinfile: line="source /home/pavel/.rvm/scripts/rvm" dest="~/.bashrc" state=present
    - apt: name=bundler
      sudo: True
    - command: "touch /home/pavel/.gemrc"
      sudo: True
    - lineinfile: 'line="gem: --no-ri --no-rdoc" dest="~/.gemrc"'
    #- file: src={{ curdir }}/files/{{ item }} dest=~/.{{ item }} state=link
    #sudo: True
    #with_items:
    #    - gitignore
    #    - vimrc
    #    - bashrc
    - command: 'git config --global core.excludesfile ~/.gitignore'
    - apt: name=git-flow
      sudo: True
    - apt: name=vim
      sudo: True
    - apt: name=vim
      tags: vim
    - file: path="~/.vbuf" state=touch
      sudo: True
    - git: repo=https://github.com/ingydotnet/yaml-vim.git
           dest=~/vim_files
      tags: vim
    - file: path=~/.vim/syntax state=directory
    - copy: src=~/vim_files/syntax/yaml.vim dest=~/.vim/syntax/yaml.vim
      tags: vim
    - file: path=~/.vim/scripts state=directory
      tags: vim
    - copy: src=~/vim_files/{{ item }} dest=~/.vim/scripts/{{ item }}
      tags: vim
      with_items:
        - yamlsort.vim
        - yamlsort.rb
    - file: path=~/vim_files state=absent
    - command: git config --global core.editor "vim"
      tags: vim
    - git: repo=https://github.com/gmarik/vundle.git 
           dest=~/.vim/bundle/vundle 
    - command: "vim +BundleInstall +qall"
    #- copy: src={{ curdir }}/files/pg_hba.conf dest=/etc/postgresql/9.5/main/pg_hba.conf
    - apt: name={{ item }}
      sudo: True
      with_items:
        - libpq-dev
        - libmagickwand-dev
        - nodejs
        - npm
    - command: "dpkg --add-architecture i386"
      sudo: True
    #- apt_repository: repo="deb http://archive.canonical.com/ $(lsb_release -sc) partner"
    #  sudo: True
    #- command: "npm config set registry http://registry.npmjs.org/"
    - command: sudo apt-get -f install
    - apt: name={{ item }}
      sudo: True
      with_items:
        - gimp
        - gnome-tweak-tool
    - command: pip install --upgrade pip
      sudo: True
    - git: repo=https://github.com/wakatime/gedit-wakatime dest=~/gedit-wakatime
      tags: wakatime
    - get_url: url=https://bootstrap.pypa.io/get-pip.py dest=~/get-pip.py
      tags: wakatime
    - command: python ~/get-pip.py
      tags: wakatime
    - command: python ~/gedit-wakatime/install.py
      tags: wakatime
    - name: Add Heroku release key for package verification
      sudo: yes
      action: apt_key url=https://toolbelt.heroku.com/apt/release.key state=present
      tags: heroku

    #- name: Add Heroku APT repository
    #  tags: heroku
    #  sudo: yes
    #  action: apt_repository repo="deb http://toolbelt.heroku.com/ubuntu ./" state=present

    #- name: Install Heroku toolbelt
    #  tags: heroku
    #  sudo: yes
    #  action: apt name=heroku-toolbelt state=latest update_cache=yes cache_valid_time=86400
