---
- hosts: all
  vars:
    name: "Pavel Kalashnikov"
    email: "kalashnikovisme@gmail.com"
  tasks: 
    - name: Install first batch of needed packages
      apt:
        pkg:
        - htop 
        - graphviz 
        - git 
        - curl 
        - build-essential 
        - openssl 
        - libreadline6-dev
        - zlib1g 
        - zlib1g-dev 
        - libssl-dev 
        - libyaml-dev 
        - libreadline-dev 
        - libsqlite3-dev 
        - libxslt1-dev 
        - libgdbm-dev 
        - libncurses5-dev 
        - automake 
        - libtool 
        - bison 
        - libffi-dev 
        - libsqlite3-0 
        - libmysqlclient-dev 
        - aptitude
        - openvpn
        - vim-nox
        - vim-gtk
        - vim-gtk3
        - vim-athena
        - vlc
        - postgresql
        - unetbootin
        - gparted
        - arduino
        - arduino-core
        - ffmpeg
        - docker.io
      become: yes
    - command: git config --global user.email "{{ email }}"
    - command: git config --global user.name "{{ name }}"
    - command: "gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB"
    - shell: "curl -sSL https://get.rvm.io | bash -s stable --ruby"
    - command: "touch /home/pavel/.gemrc"
    - lineinfile: 'line="gem: --no-ri --no-rdoc" dest="~/.gemrc"'
    - command: 'git config --global core.excludesfile ~/.gitignore'
    - apt:
        pkg:
          - git-flow
          - vim
      become: true
    - file:
        path: "~/.vbuf"
        state: touch
    - git:
        repo: https://github.com/ingydotnet/yaml-vim.git
        dest: ~/vim_files
      tags: vim
    - file:
        path: ~/.vim/syntax
        state: directory
    - copy:
        src: ~/vim_files/syntax/yaml.vim
        dest: ~/.vim/syntax/yaml.vim
      tags: vim
    - file:
        path: ~/.vim/scripts
        state: directory
      tags: vim
    - copy:
        src: ~/vim_files/{{ item }}
        dest: ~/.vim/scripts/{{ item }}
      tags: vim
      with_items:
        - yamlsort.vim
        - yamlsort.rb
    - file:
        path: ~/vim_files
        state: absent
    - command: git config --global core.editor "vim"
      tags: vim
    - git:
        repo: https://github.com/gmarik/vundle.git 
        dest: ~/.vim/bundle/vundle 
    - file:
        path: ~/.vim/plugin/
        state: directory
        force: yes
    - command: "vim +BundleInstall +qall"
    - copy:
        src: "{{ curdir }}/files/pg_hba.conf"
        dest: /etc/postgresql/12/main/pg_hba.conf
      become: true
    - apt:
        pkg:
          - libpq-dev
          - libmagickwand-dev
          - nodejs
          - npm
          - yarn
      become: true
    - command: "dpkg --add-architecture i386"
      become: true
    - command: sudo apt-get -f install
    - apt:
        pkg:
          - gimp
          - gnome-tweak-tool
      become: true
    - shell: "wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -"
    - shell: "sudo sh -c 'echo \"deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main\" >> /etc/apt/sources.list.d/google-chrome.list'"
    - shell: "sudo apt-get update"
    - shell: "sudo apt-get install google-chrome-stable"
    - copy:
        src: "{{ curdir }}/files/bashrc"
        dest: "~/.bashrc"
    - command: "/bin/bash -lic 'source ~/.bashrc'"
    - copy:
        src: "{{ curdir }}/files/gitignore"
        dest: "~/.gitignore"
    - name: Install foo
      community.general.snap:
        name:
          - rocketchat-desktop
