---
- hosts: all
  tasks:
    - file: path=~/.vimrc state=absent
    - copy: src={{ curdir }}/files/vimrc dest=~/.vimrc
    - command: "vim +BundleInstall +qall"
    - command: "vim +PluginInstall +qall"
