---
- hosts: all
  tasks:
    - lineinfile: dest=~/.bashrc state=present line={{ item }}
      with_items:
        - alias gc='git commit'
        - alias gp='git push'
        - alias gpt='git push --tags'
        - alias gs='git status'
        - alias gd='git diff'
        - alias gap='git add -p'
        - alias ga='git add .'
        - alias gco='git checkout'
        - alias gcF='git commit --amend'
        - alias gbc='git checkout -b'
        - alias gfs='git flow feature start'
        - alias gff='git flow feature finish'
        - alias grs='git flow release start'
        - alias grf='git flow release finish'
        - alias gups='git push --set-upstream origin'
        - alias glt='git describe --abbrev=0 --tags'
        - alias gplr='git pull --rebase'
        - alias dr='git checkout develop && git push && git checkout master && git push && git push --tags && cap production deploy'
        - alias dra='git checkout develop && git push && git checkout master && git push && git push --tags && make deploy'
        - alias dro='git checkout develop && git push && git checkout master && git push && git push --tags && cap deploy'
        - alias drh='git checkout develop && git push && git checkout master && git push && git push --tags && git push heroku master && heroku run rake db:migrate'
        - alias pg='git checkout develop && git push && git checkout master && git push && git push --tags && rm  *.gem && gem build $(basename "$PWD").gemspec && gem push *.gem'
        - alias vpn='sudo openvpn --config'
        - alias fuck='sudo !!'
        - alias mngs='sudo systemctl start mongodb && mongod && sudo service mongodb status'
        - alias gpdm='git push origin develop && git push origin master'
        - alias gce='git commit --allow-empty -m "Empty commit"'
