---
- hosts: all
  tasks:
    - lineinfile: dest=~/.bashrc state=present line={{ item }}
      with_items:
        - alias gc='git commit'
        - alias gp='git push'
        - alias gpt='git push --tags'
        - alias gs='git status'
        - alias gd='git diff'
        - alias gap='git add -p'
        - alias ga='git add .'
        - alias gco='git checkout'
        - alias gf='git fetch origin && git checkout'
        - alias gcF='git commit --amend'
        - alias gbc='git checkout -b'
        - alias gfs='git flow feature start'
        - alias gff='git flow feature finish'
        - alias ghs='git flow hotfix start'
        - alias ghf='git flow hotfix finish'
        - alias grs='git flow release start'
        - alias grf='git flow release finish'
        - alias gups='git push --set-upstream origin'
        - alias glt='git describe --abbrev=0 --tags'
        - alias gplr='git pull --rebase'
        - alias pga='for D in *; do [ -d "${D}" ] && cd "${D}" && (pg || true) && cd ..;  done'
        - alias fuck='sudo !!'
        - alias opengem='_() { cd $(rvm gemdir)/gems/$(gem list | grep -o "$1 (\([0-9]\.*\)*" | sed "s/ (/-/"); }; _'
        - alias dm="gp && gco main && gp && gpt && gco develop"
        - alias gce='git commit --allow-empty -m "Empty commit"'
