---
- hosts: all
  vars:
    git_flow_dir_path: /home/$USER/git_flow/
  tasks:
    - name: Create directory
      file:
        path: "{{ git_flow_dir_path }}"
        state: directory

    - name: Copy start release file
      copy:
        src: ../files/start_release
        dest: "{{ git_flow_dir_path }}/start_release"
        mode: u=rwx,g=r,o=r

    - name: Copy finish release file
      copy:
        src: ../files/finish_release
        dest: "{{ git_flow_dir_path }}/finish_release"
        mode: u=rwx,g=r,o=r

    - lineinfile:
        dest: /home/$USER/.bashrc
        state: present
        line: "{{ item }}"
      with_items:
        - alias gc='git commit'
        - alias gp='git push'
        - alias gpt='git push --tags'
        - alias gs='git status'
        - alias gd='git diff'
        - alias gap='git add -p'
        - alias ga='git add .'
        - alias gco='git checkout'
        - alias gcF='git commit --amend'
        - alias gbc='git checkout -b'
        - alias gfs='git flow feature start'
        - alias gff='git flow feature finish'
        - alias ghs='git flow hotfix start'
        - alias ghf='git flow hotfix finish'
        - alias grs='~/git_flow/start_release'
        - alias grf='~/git_flow/finish_release'
        - alias gups='git push --set-upstream origin'
        - alias glt='git describe --abbrev=0 --tags'
        - alias gplr='git pull --rebase'
        - alias pga='for D in *; do [ -d "${D}" ] && cd "${D}" && (pg || true) && cd ..;  done'
        - alias fuck='sudo !!'
        - alias opengem='_() { cd $(rvm gemdir)/gems/$(gem list | grep -o "$1 (\([0-9]\.*\)*" | sed "s/ (/-/"); }; _'
        - alias dm="gp && gco main && gp && gpt && gco develop"
        - alias gce='git commit --allow-empty -m "Empty commit"'
