- hosts: all
  tasks:
    - name: "1Password CLI: Install (Ubuntu)"
      block:
        - name: "1Password CLI: Add apt signing key"
          apt_key:
            url: https://downloads.1password.com/linux/keys/1password.asc
            keyring: /usr/share/keyrings/1password-archive-keyring.gpg
            state: present

        - name: "1Password CLI: Add apt repository"
          apt_repository:
            repo: "deb [arch={{ ansible_architecture | replace('x86_64', 'amd64') }} signed-by=/usr/share/keyrings/1password-archive-keyring.gpg] https://downloads.1password.com/linux/debian/{{ ansible_architecture | replace('x86_64', 'amd64') }} stable main"
            filename: 1password
            state: present

        - name: "1Password CLI: Install package"
          apt:
            name: 1password-cli
            update_cache: yes
            state: present
      become: yes
      when: ansible_pkg_mgr == 'apt'

    - name: "1Password CLI: Install (Omarchy)"
      package:
        name: 1password-cli
        state: present
      become: yes
      when: ansible_pkg_mgr == 'pacman'
