- hosts: all
  tasks:
    - name: Generate new ssh key
      command:
        - echo | ssh-keygen -t ed25519 -C "kalashnikovisme@gmail.com"
        - eval "$(ssh-agent -s)"
        - ssh-add ~/.ssh/id_ed25519
