- hosts: all
  become_user: root
  tasks:
    - name: Install obs virtual camera (Debian)
      become: true
      package:
        name:
          - v4l2loopback-dkms
      when: ansible_pkg_mgr == 'apt'

    - name: Update repository for OBS (Debian)
      shell: sudo add-apt-repository ppa:obsproject/obs-studio
      when: ansible_pkg_mgr == 'apt'

    - name: Refresh packages (Debian)
      shell: sudo apt -y update
      when: ansible_pkg_mgr == 'apt'

    - name: Install obs (Debian)
      package:
        name:
          - obs-studio
      become: true
      when: ansible_pkg_mgr == 'apt'

    - name: Install obs (Omarchy)
      package:
        name:
          - obs-studio
      become: true
      when: ansible_pkg_mgr == 'pacman'
