- hosts: all
  tasks:
    - apt:
        pkg:
          - software-properties-common
    - command: add-apt-repository ppa:appimagelauncher-team/stable
    - command: apt-get update
    - apt:
        pkg:
          - appimagelauncher
