---
- hosts: all
  tasks:
    - name: Install nvm
      shell: curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash

    - name: Check nvm installation
      stat:
        path: "{{ ansible_env.HOME }}/.nvm/nvm.sh"
      register: stat_result

    - name: Fail if nvm is not installed
      fail:
        msg: "nvm installation failed: {{ ansible_env.HOME }}/.nvm/nvm.sh not found."
      when: not stat_result.stat.exists

    - name: Install latest LTS Node.js via nvm
      shell: |
        export NVM_DIR="{{ ansible_env.HOME }}/.nvm"
        [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
        nvm install --lts
        nvm alias default 'lts/*'
        nvm use --lts
      args:
        executable: /bin/bash

    - name: Ensure nvm is initialized in bash and zsh
      blockinfile:
        path: "{{ item }}"
        create: true
        marker: "# {mark} ANSIBLE MANAGED BLOCK: NVM"
        block: |
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
      loop:
        - "{{ ansible_env.HOME }}/.bashrc"
        - "{{ ansible_env.HOME }}/.zshrc"
        - "{{ ansible_env.HOME }}/.profile"

    - name: Add Yarn apt key
      become: yes
      shell: curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      when: ansible_pkg_mgr == 'apt'

    - name: Add Yarn repository
      become: yes
      shell: echo "deb https://dl.yarnpkg.com/debian stable main" | tee /etc/apt/sources.list.d/yarn.list
      when: ansible_pkg_mgr == 'apt'

    - name: Install yarn (Debian)
      become: yes
      apt:
        name: yarn
        update_cache: yes
      when: ansible_pkg_mgr == 'apt'

    - name: Install yarn (Arch)
      become: yes
      pacman:
        name: yarn
        state: present
      when: ansible_pkg_mgr == 'pacman'
