- hosts: all
  tasks:
    - name: "Ruby: RVM download"
      command: curl -sSL https://get.rvm.io -o ./rvm_install.bash

    - name: "Ruby: RVM installation"
      command: bash ./rvm_install.bash
      
    - name: Add gemrc file
      copy:
        content: |
          gem: --no-ri --no-rdoc
        dest: /home/$USER/.gemrc
