- hosts: all
  vars:
    docker_compose_version: "2.19.1"
  become_user: root
  tasks: 
    - name: "Docker: Install prerequisites (Ubuntu)"
      package:
        name:
          - ca-certificates
          - gnupg
          - curl
      become: true
      when: ansible_pkg_mgr == 'apt' and ansible_distribution == 'Ubuntu'
    - name: "Docker: prepare installation"
      command: sh ./docker/prepare_installation.sh
      become: true
      when: ansible_pkg_mgr == 'apt' and ansible_distribution == 'Ubuntu'
    - name: "Docker: install (Ubuntu)"
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      become: true
      when: ansible_pkg_mgr == 'apt' and ansible_distribution == 'Ubuntu'
    - name: Post-install docker actions. Create docker group
      group:
        name: docker
        state: present
      when: ansible_distribution == 'Ubuntu'
    - name: Check for docker compose plugin location
      stat:
        path: "{{ item }}"
      register: docker_compose_plugin_stat
      loop:
        - /usr/libexec/docker/cli-plugins/docker-compose
        - /usr/lib/docker/cli-plugins/docker-compose
      when: ansible_distribution == 'Ubuntu'
    - name: Set docker compose plugin path
      set_fact:
        docker_compose_plugin_path: "{{ item.stat.path }}"
      when:
        - ansible_distribution == 'Ubuntu'
        - item.stat.exists
      loop: "{{ docker_compose_plugin_stat.results | default([]) }}"
    - name: Link docker-compose to installed plugin
      file:
        src: "{{ docker_compose_plugin_path }}"
        dest: /usr/local/bin/docker-compose
        state: link
      become: true
      when:
        - ansible_distribution == 'Ubuntu'
        - docker_compose_plugin_path is defined
    - name: "Install docker-compose version: {{ docker_compose_version }}"
      get_url:
        url: "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: "0755"
        timeout: 30
      register: docker_compose_download
      retries: 3
      delay: 5
      until: docker_compose_download is succeeded
      become: true
      when:
        - ansible_distribution == 'Ubuntu'
        - docker_compose_plugin_path is not defined
