- hosts: all
  vars:
    docker_compose_version: "2.19.1"
  become_user: root
  tasks: 
    - name: "Docker: Install prerequisites (Debian)"
      package:
        name:
          - ca-certificates
          - gnupg
          - curl
      become: true
      when: ansible_pkg_mgr == 'apt'
    - name: "Docker: prepare installation"
      command: sh ./docker/prepare_installation.sh
      become: true
      when: ansible_pkg_mgr == 'apt'
    - name: "Docker: install (Debian)"
      package:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
      become: true
      when: ansible_pkg_mgr == 'apt'

    - name: "Docker: install (Arch)"
      package:
        name:
          - docker
          - docker-compose
      become: true
      when: ansible_pkg_mgr == 'pacman'
    - name: Post-install docker actions. Create docker group
      group:
        name: docker
        state: present
    - name: "Install docker-compose version: {{ docker_compose_version }}"
      command: 'curl -L "https://github.com/docker/compose/releases/download/v{{ docker_compose_version }}/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose'
      become: true
    - name: Add execute permissions
      become: true
      file:
        path: /usr/local/bin/docker-compose
        mode: +x
