- hosts: all
  become_user: root
  vars:
    name: "Pavel Kalashnikov"
    email: "kalashnikovisme@gmail.com"
  tasks:
    - name: Install git
      command: apt-get install -y git-core
    - command: git config --global user.email "{{ email }}"
    - command: git config --global user.name "{{ name }}"
    - command: git config --global core.excludesfile ~/.gitignore
    - command: git config --global core.editor "vim"
    - command: git config --global init.defaultBranch "main"
    - name: Install git-flow
      command: apt-get -y install git-flow
    - copy:
        src: "./files/gitignore"
        dest: "~/.gitignore"