- hosts: all
  vars:
    name: "Pavel Kalashnikov"
    email: "kalashnikovisme@gmail.com"
  tasks:
    - name: Install git
      package:
        name:
          - git
    - command: git config --global user.email "{{ email }}"
    - command: git config --global user.name "{{ name }}"
    - command: git config --global core.excludesfile ~/.gitignore
    - command: git config --global core.editor "vim"
    - command: git config --global init.defaultBranch "main"
    - copy:
        src: "../files/gitignore"
        dest: "~/.gitignore"
