---
- hosts: all
  tasks:
    - name: Install Neovim
      become: yes
      package:
        name: neovim
        state: present

    - name: Ensure pynvim Python module is installed on Omarchy
      pip:
        name: pynvim
        state: latest
        executable: pip3
        extra_args: --user
      when: ansible_env.OS is defined and ansible_env.OS == "omarchy"

    - name: Ensure ~/.config/nvim directory exists
      file:
        path: ~/.config/nvim/
        state: directory
        mode: '0755'

    - name: Remove legacy init.vim when using LazyVim on Omarchy
      file:
        path: ~/.config/nvim/init.vim
        state: absent
      when: ansible_env.OS is defined and ansible_env.OS == "omarchy"

    - name: Reset LazyVim Lua directory on Omarchy
      file:
        path: ~/.config/nvim/lua
        state: absent
      when: ansible_env.OS is defined and ansible_env.OS == "omarchy"

    - name: Deploy LazyVim init.lua on Omarchy
      copy:
        src: "{{ playbook_dir }}/../files/omarchy/init.lua"
        dest: ~/.config/nvim/init.lua
        mode: '0644'
      when: ansible_env.OS is defined and ansible_env.OS == "omarchy"

    - name: Deploy LazyVim Lua config on Omarchy
      copy:
        src: "{{ playbook_dir }}/../files/omarchy/lua/"
        dest: ~/.config/nvim/lua/
        mode: preserve
        directory_mode: '0755'
      when: ansible_env.OS is defined and ansible_env.OS == "omarchy"

    - name: Copy existing init.vim to ~/.config/nvim/init.vim
      copy:
        src: ../files/init.vim
        dest: ~/.config/nvim/init.vim
        remote_src: yes
      when: ansible_env.OS is not defined or ansible_env.OS != "omarchy"

    - name: Replace instances of ~/.vim with ~/.config/nvim in init.vim
      lineinfile:
        path: ~/.config/nvim/init.vim
        regexp: 'let data_dir = has(.nvim.) ? stdpath(.data.) . /site : ~/.vim'
        line: 'let data_dir = has("nvim") ? stdpath("data") . "/site" : "~/.config/nvim"'
      when: ansible_env.OS is not defined or ansible_env.OS != "omarchy"

    - name: Ensure vim-plug is installed for Neovim
      shell: |
        curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
        https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
      args:
        creates: ~/.local/share/nvim/site/autoload/plug.vim
      when: ansible_env.OS is not defined or ansible_env.OS != "omarchy"

    - name: Check if Neovim is installed successfully
      command: nvim --version
      register: nvim_version

    - name: Debug output to ensure Neovim is working
      debug:
        var: nvim_version.stdout

    - name: Install LazyVim plugins on Omarchy
      shell: nvim --headless "+Lazy! sync" +qa
      when: ansible_env.OS is defined and ansible_env.OS == "omarchy"

    - name: Test Neovim configuration by opening Neovim
      shell: nvim +PlugInstall +qall
      when: ansible_env.OS is not defined or ansible_env.OS != "omarchy"

