---
- hosts: all
  tasks:
    - name: Copy .vimrc file
      copy:
        src: ../files/vimrc
        dest: ~/.vimrc
    - name: Install Vim and needed stuff
      become: true
      package:
        name:
          - vim
          - vim-nox
          - vim-gtk
          - vim-gtk3
          - vim-athena
    - git:
        repo: https://github.com/ingydotnet/yaml-vim.git
        dest: ~/vim_files
    - file:
        path: ~/.vim/syntax
        state: directory
    - copy:
        src: ~/vim_files/syntax/yaml.vim
        dest: ~/.vim/syntax/yaml.vim
      tags: vim
    - file:
        path: ~/.vim/scripts
        state: directory
      tags: vim
    - copy:
        src: ~/vim_files/{{ item }}
        dest: ~/.vim/scripts/{{ item }}
      tags: vim
      with_items:
        - yamlsort.vim
        - yamlsort.rb
    - file:
        path: ~/vim_files
        state: absent
    - file:
        path: ~/.vim/plugin/
        state: directory
        force: yes
    - file:
        path: /home/$USER/.vim
        state: directory
    - copy:
        src: "../files/vimrc"
        dest: "~/.vimrc"
    - name: Install deoplete (Debian)
      package:
        name:
          - python3-pip
      when: ansible_pkg_mgr == 'apt'

    - name: Install deoplete (Arch)
      package:
        name:
          - python-pip
      when: ansible_pkg_mgr == 'pacman'
    - name: Install pynvim and msgpack (Debian)
      become: true
      package:
        name:
          - python3-pynvim
          - python3-msgpack
      when: ansible_pkg_mgr == 'apt'

    - name: Install pynvim and msgpack (Arch)
      become: true
      package:
        name:
          - python-pynvim
          - python-msgpack
      when: ansible_pkg_mgr == 'pacman'
