set nu
set expandtab
set sw=2
set sts=2
let g:fuzzy_ignore = "gems/*"
set nocompatible
filetype off
let data_dir = has('nvim') ? stdpath('data') . '/site' : '~/.vim'
if empty(glob(data_dir . '/autoload/plug.vim'))
  silent execute '!curl -fLo '.data_dir.'/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
  autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif
call plug#begin()
Plug 'scrooloose/nerdtree'
Plug 'kchmck/vim-coffee-script'
Plug 'scrooloose/syntastic'
Plug 'Shougo/neocomplete.vim'
Plug 'tpope/vim-rails'
Plug 'slim-template/vim-slim'
Plug 'isRuslan/vim-es6'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-surround'
Plug 'elixir-lang/vim-elixir'
Plug 'leafgarland/typescript-vim'
Plug 'mxw/vim-jsx'
Plug 'wakatime/vim-wakatime'
Plug 'sebdah/vim-delve'
Plug 'posva/vim-vue'
Plug 'maxmellon/vim-jsx-pretty'
Plug 'tpope/vim-commentary'
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
Plug 'junegunn/fzf.vim'
call plug#end()
syntax enable
filetype plugin indent on
imap <F2> <Esc>:w<CR>
map <F2> <Esc>:w<CR>
imap <F3> <Esc>:q!<CR>
map <F3> <Esc>:q!<CR>
imap <F4> <Esc>:wq<CR>
map <F4> <Esc>:wq<CR>
imap <F5> <Esc>:set paste<CR>
map <F5> <Esc>:set paste<CR>
imap <F6> <Esc>:set nopaste<CR>
map <F6> <Esc>:set nopaste<CR>
imap <F7> <Esc>:%s/:\([^ ]*\)\(\s*\)=>/\1:/g<CR>
map <F7> <Esc>:%s/:\([^ ]*\)\(\s*\)=>/\1:/g<CR>
imap <F8> <Esc>:s#\%($\%(\k\+\)\)\@<=_\(\k\)#\u\1#g<CR>
map <F8> <Esc>:s#\%($\%(\k\+\)\)\@<=_\(\k\)#\u\1#g<CR>
nmap <F9> :%!html2haml --erb 2> /dev/null<CR>:set ft=haml<CR>
vmap <F9> :!html2haml --erb 2> /dev/null<CR>
set relativenumber
"allow to copy/paste between VIM instances
" "copy the current visual selection to ~/.vbuf
vmap <F10>y :w! ~/.vbuf<CR>
" "copy the current line to the buffer file if no visual selection
nmap <F10>y :.w! ~/.vbuf<CR>
" "paste the contents of the buffer file
nmap <F10>p :r ~/.vbuf<CR>
map <C-p> :NERDTreeToggle<CR>
nmap <silent> <C-k> :wincmd k<CR>
nmap <silent> <C-j> :wincmd j<CR>
nmap <silent> <C-h> :wincmd h<CR>
nmap <silent> <C-l> :wincmd l<CR>
let g:neocomplete#enable_at_startup = 2
au BufRead,BufNewFile *.thor set syntax=ruby
au BufRead,BufNewFile *.simplecov set syntax=ruby
au BufRead,BufNewFile *.es6 set filetype=javascript
au BufRead,BufNewFile *.vue set filetype=javascript
au BufRead,BufNewFile *.vue set syntax=javascript
au BufRead,BufNewFile *.go set tabstop=2
au BufRead,BufNewFile Makefile set tabstop=2
au BufRead,BufNewFile Dockerfile* set syntax=dockerfile
au BufRead,BufNewFile .eslintrc set syntax=json
au BufRead,BufNewFile *.tsx set syntax=typescript
autocmd FileType vue noremap <buffer> <C-f> :%!vue-formatter<CR>
set :hlsearch
